### ISSUE TITLE
Make PyYaml module available in Python Evaluation

### ISSUE THREAD

**Issue by mmumshad** [udemy/coding-challenge#1]
What does it take to make an additional python library - PyYaml - to be made available on the Python Evaluation tests for Coding Exercises?

I am in the process of creating a coding exercise to parse YAML files. My coding evaluation need to be able to parse YAML file using PyYaml. However I get the "module not found error". Can anyone help?

**Comment by arski** [comment]
Hi there, i believe the name of this repo is confusing, its not about thecoding exercises on our platform. Please check support.udemy.com for your request. Thanks!
